# Generated by Django 4.2.3 on 2023-07-08 21:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MOVING_UP", "Moving Up"),
                            ("MOVING_DOWN", "Moving Down"),
                            ("NOT_WORKING", "Not Working"),
                            ("MAINTENANCE", "Maintenance"),
                            ("AVAILABLE", "Available"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "door_status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSE", "Close")], max_length=10
                    ),
                ),
                ("current_floor", models.IntegerField()),
                (
                    "destination_floors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElevatorSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(default=dict)),
                ("elevators_number", models.IntegerField()),
                ("max_queue_size", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(default=dict)),
                ("current_floor", models.IntegerField()),
                ("destination_floor", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("NEGLECTED", "Neglected"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "elevator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="elevators.elevator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="elevator",
            name="elevator_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="elevators.elevatorsystem",
            ),
        ),
    ]
